CUREMD_DAT_LOGIN_ASP = 'https://releaseapp01.curemd.com/curemd/datLogin.asp'
Username='uadph'
Password='as'
Expected_URL_Of_10G='https://releaseapp01.curemd.com/curemd/datCureMD.aspx'
patient_btn="//a[@id='patientBtn']"
patient_acc_no = "19632331239377"
patient_search_body_frame="//iframe[@id='fraCureMD_Body']"
patient_search_field="//input[@id='txtAccount_Number']"
patient_search_btn="//td[@title='Search Patient']"
patient_link = "//a[@id='anchorPatientName83186']"
patient_mnu_frame = "//iframe[@id='fraCureMD_Patient_Menu']"
patient_blng_btn = "//a[@id='Billing_anchor']"
patient_adv_btn = "//a[@id='Patient_Advances_anchor']"
collect_adv_btn = "//a[@id='collectAdv']"
paymethod_select = "//select[@id='ddlPmntTp']"
payment_option = "CREDIT CARD"
payment_lnk = "//a[contains(@onclick, \"openOnlinePaymentPopup('CC')\")]"
payment_window ="//iframe[@id='DynamicBHdialogbox']"
payment_card_num_frm = "//iframe[contains(@name,'card-number')]"
payment_card_num_fld = "//input[contains(@name,'cardNumber')]"
payment_card_expiry_frm = "//iframe[@name='card-expiration']"
payment_card_expiry_fld = "//input[contains(@class,'card-expiration')]"
payment_card_cvv_frm = "//iframe[@name='card-cvv']"
payment_card_cvv_fld = "//input[contains(@class,'card-cvv')]"
payment_amount_fld = "//*[@id='txtAmount']"
make_payment_btn_frm = "//iframe[contains(@name,'submit')]"
make_payment_btn = "//button[@class='submit' and contains(text(), 'Process Payment')]"
success_payment_msg = "//div[@id='PaymentSuccess']"
decline_payment_msg = "//div[@id='divErrorMessage']"
card_number_non_surcharge="4012000098765439"
card_number_surcharge="5424180001234506"
card_expiry="12/26"
card_cvv="599"
full_amount="16.79"
partial_amount="13.17"
decline_amount="13.02"
card_on_file_checkbox="Save card on file"
use_till_date_fld="#txtUseUntil"
use_till_date="12/31/2029"
max_transaction_amount_fld='#txtMaxSingleAmount'
max_transaction_amount="1000.00"
signature_frm="iframe#DynamicDialogBox, iframe[src*='CardOnFileAgreement']"
signature_img="#imgScriptelSignature, img[alt*='signature'], img[title*='signature'], img[src*='signature']"
signature_fld="#txtInitials"
card_signature="US Save Card"
continue_btn_locator="#imgContinue"
card_on_file_amount_fld="//input[@id='txtCardOnFileAmount']"
process_payment_btn_loc="//input[@id='btnSavedCardPayment']"

